### ISSUE TITLE
can't connect to localhost

### ISSUE THREAD

**Issue by anwain** [perak/meteor-mqtt-collection#1]
Hi Perak,

Trying to connect to localhost:1883 for messages coming from node red, but I can't see any additions to my collection. Tried both "mqtt://localhost:1883" and "tcp://localhost:1883" to no avail.

How do you use your package for localhost connections?

Thanks

**Comment by perak** [comment]
@Anwain 
- What OS and mosquitto version are you using?
- Are you sure firewall doesn't make troubles?

...

**Comment by anwain** [comment]
Ubuntu 14.04. Mosquitto 0.13 (might need updating) 
I can connect to topics via the terminal

**Comment by perak** [comment]
Please try to install fresh version of mosquitto via PPA, as described in http://mosquitto.org/download/

That should work.

Please let me know for the results.

**Comment by anwain** [comment]
Hey, I updated to v1.4.2 and still no luck. Tried to use the same code + mosquitto version on windows and it works there without a problem.

**Comment by perak** [comment]
interesting... I am curious about this problem, will try the same setting
on ubuntu tomorrow

**Comment by anwain** [comment]
Got it to work. Killed the background mosquitto task and launched it separately in a new terminal

**Comment by perak** [comment]
So, if mosquitto runs as a daemon you cannot connect, but if you run it as
application than it works? (or maybe running daemon was old version?)

**Comment by anwain** [comment]
I think the running daemon was the old version, as every time since it has worked.

**Comment by perak** [comment]
OK, thanks. Closing this issue.
