### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by sakulstra** [perak/meteor-mqtt-collection#3]
Hello there, is there any possibility to timestamp the collection entries?
Best Regards,
Lukas

**Comment by perak** [comment]
@sakulstra you can add `matb33:collection-hooks` package to your application and somewhere in server scope add:

```
YourCollectionName.before.insert(function (userId, doc) {
  doc.createdAt = Date.now();
});
```

**Comment by sakulstra** [comment]
Could have find this solution on my own, sry
Thanks for your efforts!
