### ISSUE TITLE
Messaggi.mqttConnect is not a function

### ISSUE THREAD

**Issue by hellzakk** [perak/meteor-mqtt-collection#4]
@perak 

Hi, im running meteor on a raspberry pi 3

Hi, i've added your package to my project
$ meteor add perak:mqtt-collection

In project/lib/collections/posts.js i've added
Messaggi = new Mongo.Collection("messaggi");
Messaggi.mqttConnect("mqtt://localhost:1833", ["devices"], {}, {})};

In the browser console i get
TypeError: Messaggi.mqttConnect is not a function

Im new to Meteor and javascript, can you help me to figure out how to resolve this?

**Comment by perak** [comment]
@hellzakk try to add mqttConect into server startup block. Code located in `lib` dir executes both on client and server. mqttConnect must be executed on server only. So, create `server` dir in your project root and add js file containing:

```
Meteor.startup(function() {
  mqttConnect...
});
```

Another way is: put that code into your current file but enclose it into `if(Mereor.isServer) { ... }`

**Comment by perak** [comment]
btw, try to build and run one of meteor-kitchen's IoT example apps: http://www.meteorkitchen.com/examples and see the code/modify code for your needs.

**Comment by hellzakk** [comment]
@perak youre absolutely right, i have read the instruction about the use of the mqttConnect function but i completely forgot to wrap it inside the if(Mereor.isServer) when i write the code...
I will try soon

**Comment by hellzakk** [comment]
@perak worked perfectly ;)

**Comment by perak** [comment]
👍
