### ISSUE TITLE
Overwrite problem

### ISSUE THREAD

**Issue by hellzakk** [perak/meteor-mqtt-collection#5]
@perak 

Hi, i have some arduinos that when they are connected they send this data
{id:mac,status:online}

they are inserted in the devices/mac topic of devices collection
Devices = new Mongo.Collection('devices');
Devices.mqttConnect({host:'localhost',port: 1883},["devices/+"],{},{});

So in MongoDB i have this structure
Element
- _id : E4f67J9Kaz3dsxW
- topic : devices/mac
- message + id : mac , status : online

The problem is that when i send the last will of a crashed/disconnected device
{status:offline}
it write all the message field
- message + status : offline

loosing all other data

Is there a workaraound for this or can you point me in the right direction?

Thanks you

**Comment by perak** [comment]
@hellzakk Are you writing data into collection from your code, or mqttCollection is doing that?

If you are writing data from your own code, don't forget this:

```
SomeCollection.update({ _id: "some_id" }, { status: "offline" });
```

Will **replace** entire document with `{ status: "offline" }`.

If you want to keep entire document, and change only `status` field, this is your command:

```
SomeCollection.update({ _id: "some_id" }, { $set: { status: "offline" } });
```

Mongo operator `$set` will "merge" existing document overwriting properties supplied as argument.

**Comment by hellzakk** [comment]
@perak id prefer doing that from mqttcollection because im running it from a raspberry and id like to save any cpu cicle :)

im using knolleary/pubsubclient in arduino

**Comment by perak** [comment]
@hellzakk interesting! I suggest you to share your experience in forums.meteor.com :+1:

**Comment by perak** [comment]
BTW, did you solved the problem?

**Comment by hellzakk** [comment]
@perak no atm...
mqttConnect use 2 field, topic and message... topic is the reference of the mqtt topic a message was sent to and message is the data-message itself.
If you set insert: false mqttConnect update the same document (with same topic) in MongoDB so if you get another message with same topic of another document it updates the fields and in the message you erase all previus data and insert the last one... i dont understand how to change this...

**Comment by hellzakk** [comment]
@perak ok i've tried to use matb33:collection-hooks

ive do some test with 

var test = new Mongo.Collection("test");

test.before.insert(function (userId, doc) {
  doc.createdAt = Date.now();
});

if i create a new test document with the meteor shell the test.before.insert work, but with the mqttconnect it's not working

**Update**
ok it's not considered an update even if the document not exist, the called function is 

test.before.upsert(function (userId, selector, modifier, options) {
  modifier.$set = modifier.$set || {};
  modifier.$set.modifiedAt = Date.now();
});

**Comment by perak** [comment]
@hellzakk strange. Look at this examples - it works with collection hooks:

http://example-iot.meteorfarm.com/
http://example-geiger.meteorfarm.com/

Try to build these apps, and see the source code, it should help you to find the problem.

**Comment by hellzakk** [comment]
@perak 
ok i've found the right way for this, maybe it's interesting for others

in lib/collections/devices.js

Devices = new Mongo.Collection('devices');

Devices.before.upsert(function (userId, selector, modifier, options) {
 modifier.$set = modifier.$set || {};
 modifier.$set = modifier.$set.message;
});

in server/mqtt.js

Meteor.startup(function() {
 Devices.mqttConnect({ host: 'localhost', port: 1883 }, ["devices/+"], {}, {});
});

It write/update the single parameters into the message field of the original mqttconnect document outside it

original mqttConnect document
- _id : uq3Fv5Yfbdfv456hRGB
- topic : devices/DEEDBAFEFEED
- message { param2 : value1 , param2 : value2 }

document after the Devices.before.upsert function
- _id : uq3Fv5Yfbdfv456hRGB
- topic : devices/DEEDBAFEFEED
- param2 : value1
- param2 : value2
